export * from '../specialty'
export { default as LaboratorioHero } from './LaboratorioHero'
export { default as LaboratorioServicios } from './LaboratorioServicios'
export { default as EquipoCompromiso } from './EquipoCompromiso'
export { default as ConfianzaCta } from './ConfianzaCta'
export * from './data'
