export * from '../specialty'
export { default as TiposCancer } from './TiposCancer'
export { default as LoQueOfrecemos } from './LoQueOfrecemos'
export { default as ServiciosCarruselScroll } from './ServiciosCarruselScroll'
export * from './data'
