export { default as GestionEticaHero } from './GestionEticaHero'
export { default as Compromiso } from './Compromiso'
export { default as Valores } from './Valores'
export { default as Alcance } from './Alcance'
export { default as PrincipiosAtencion } from './PrincipiosAtencion'
export { default as EticaOncologia } from './EticaOncologia'
export { default as ConductaEsperada } from './ConductaEsperada'
export { default as ModeloGestion } from './ModeloGestion'
export { default as CanalDenuncias } from './CanalDenuncias'
export { default as Documentos } from './Documentos'
export { default as Indicadores } from './Indicadores'
export { default as CTAFinal } from './CTAFinal'
export * from './data'
